### ISSUE TITLE
updated project website

### ISSUE THREAD

**Issue by gregcaporaso** [gregcaporaso/An-Introduction-To-Applied-Bioinformatics#106]
To support a few convenient features, such as tracking hits to individual pages with Google Analytics, and being able to have all contents hosted under applied-bioinformatics.org, we will start using ``nbconvert`` and hosting with gh-pages instead of using nbviewer.

A page will also be dedicated to containing all of the project tracking information, described in #97.

**Comment by jairideout** [comment]
@gregcaporaso I'm using the [SinglePaged](https://github.com/t413/SinglePaged) Jekyll theme for http://keemei.qiime.org/. The theme's readme has instructions for setup, and [here's](http://t413.com/SinglePaged/) a live demo site (which also has instructions for setup). Let me know if you need any other details or help with getting this up and running!

**Comment by gregcaporaso** [comment]
Done! See the new website at [readIAB.org](http://readIAB.org).
