### ISSUE TITLE
update to be written in python3

### ISSUE THREAD

**Issue by gregcaporaso** [gregcaporaso/An-Introduction-To-Applied-Bioinformatics#110]
IAB will be written in Python 3, but it currently only works under Python 2. This issue will track known issues, which will be added here as they're discovered. 

Current issues are:
 - [x] ``qiime-default-reference`` needs to be updated for Py2/Py3 compatibility (see [here](https://travis-ci.org/gregcaporaso/An-Introduction-To-Applied-Bioinformatics/builds/56479854))
 - [x] need to not use biom in the Biological Diversity chapter (at least before it's ported to python3 or scikit-bio), it's not used very extensively there, so this shouldn't be a big problem

**Comment by gregcaporaso** [comment]
partially addressed in #117.

**Comment by jairideout** [comment]
Fixed in #138.
