### ISSUE TITLE
should text be written in markdown and injected into notebooks?

### ISSUE THREAD

**Issue by gregcaporaso** [gregcaporaso/An-Introduction-To-Applied-Bioinformatics#125]
I'm wondering if this would be a better way to handling diffing (see problems noted in [CONTRIBUTING.md](https://github.com/gregcaporaso/An-Introduction-To-Applied-Bioinformatics/blob/master/CONTRIBUTING.md), hiding of code (#115), and maybe even hiding of text (for presentations).

**Comment by gregcaporaso** [comment]
@fperez pointed me at [ipymd](https://github.com/rossant/ipymd), which looks like it could be useful for this.

**Comment by gregcaporaso** [comment]
We're doing experiments on this in the new [proto-iab](https://github.com/gregcaporaso/proto-iab) repository, and @jairideout and @johnchase are working on [making ipymd pip-installable](https://github.com/rossant/ipymd/issues/52).

**Comment by jairideout** [comment]
ipymd is now pip-installable and [on PyPI](https://pypi.python.org/pypi/ipymd/0.1.1)! See [here](https://github.com/rossant/ipymd#installation) for installation instructions.
