### ISSUE TITLE
Problem with installing IAB

### ISSUE THREAD

**Issue by ETaSky** [gregcaporaso/An-Introduction-To-Applied-Bioinformatics#150]
Dear Dr. Caporaso,
Good afternoon! I have an issue to install IAB on my computer. I am using PC but use Anaconda to mimic linux environment. I tried to use "
pip install https://github.com/gregcaporaso/An-Introduction-To-Applied-Bioinformatics/archive/0.1.1.tar.gz"
as instructed. but got an error of "404 not found"
I checked your Github site. It seems the directory and file are not there. I was just wondering what I should do to install IAB.
Thank you very much!
Jincheng

**Comment by gregcaporaso** [comment]
Hi Jincheng, I'm in the process of getting that file posted right now. It'll be up by the end of the day. If you "Watch" this repository you'll get notification of the release, and if you [follow me on twitter](https://twitter.com/gregcaporaso) I'll be announcing it there as well. More soon...

**Comment by ETaSky** [comment]
Thanks a lot!
