### ISSUE TITLE
iab.algorithms

### ISSUE THREAD

**Issue by jg44** [gregcaporaso/An-Introduction-To-Applied-Bioinformatics#165]
Hello,
I'm getting the following error (after finally winning the battle to correctly install scikit-bio).  Where is/how do I install iab.algorithms?

Thanks....

from iab.algorithms import format_matrix

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-f830f4e48990> in <module>()
----> 1 from iab.algorithms import format_matrix

ImportError: No module named iab.algorithms

**Comment by dtran288** [comment]
How did you install scikit? I'm stuck!

**Comment by jg44** [comment]
See instructions here:  http://scikit-bio.org/  This worked for me, except I had issues with dependencies, specifically matplotlib and linking with respect to libpng.  I'm really not the one to be giving advice though -- I'm more or less new to python.

**Comment by gregcaporaso** [comment]
Have you guys using Anaconda for setting up your python environment? It's
by far the easiest way. I can follow up more tomorrow, on my phone right
now.

**Comment by gregcaporaso** [comment]
Quick follow up on this. I'm thinking that I'll start recommend miniconda for installing IAB. The steps would be as follows:

1. Install miniconda, see [here](http://conda.pydata.org/miniconda.html). This will let you easily set up a very powerful and configurable python 2/3 development environment.
2. Install the IPython Notebook via miniconda (``conda install ipython-notebook``).
3. Install scikit-bio via miniconda (``conda install scikit-bio``). 
4. Then, follow the install instructions for installing IAB [here](http://readiab.org/book/latest/1/1#3). 

@dtran288, @jg44 would you be willing to try this out and let me know how it works for you?  If this seems like it's working, I'll simplify this in the future.

**Comment by dtran288** [comment]
@gregcaporaso The things above installed alright, but when I run this line:

pip install https://github.com/gregcaporaso/An-Introduction-To-Applied-Bioinformatics/archive/0.1.1.tar.gz

I get this long error:

Collecting https://github.com/gregcaporaso/An-Introduction-To-Applied-Bioinformatics/archive/0.1.1.tar.gz
/home/qiime/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/home/qiime/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://github.com/gregcaporaso/An-Introduction-To-Applied-Bioinformatics/archive/0.1.1.tar.gz (5.1MB)
    100% |████████████████████████████████| 5.1MB 40kB/s 
Collecting scikit-bio<0.3.0,>=0.2.3 (from An-Introduction-To-Applied-Bioinformatics==0.1.1)
/home/qiime/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached scikit-bio-0.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-AHAZo7/scikit-bio/setup.py", line 16, in <module>
        import numpy as np
      File "/home/qiime/qiime_software/numpy-1.7.1-release/lib/python2.7/site-packages/numpy/__init__.py", line 137, in <module>
        import add_newdocs
      File "/home/qiime/qiime_software/numpy-1.7.1-release/lib/python2.7/site-packages/numpy/add_newdocs.py", line 9, in <module>
        from numpy.lib import add_newdoc
      File "/home/qiime/qiime_software/numpy-1.7.1-release/lib/python2.7/site-packages/numpy/lib/__init__.py", line 4, in <module>
        from type_check import *
      File "/home/qiime/qiime_software/numpy-1.7.1-release/lib/python2.7/site-packages/numpy/lib/type_check.py", line 8, in <module>
        import numpy.core.numeric as _nx
      File "/home/qiime/qiime_software/numpy-1.7.1-release/lib/python2.7/site-packages/numpy/core/__init__.py", line 5, in <module>
        import multiarray
    ImportError: /home/qiime/qiime_software/numpy-1.7.1-release/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: PyUnicodeUCS4_AsUnicodeEscapeString
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-AHAZo7/scikit-bio

**Comment by gregcaporaso** [comment]
@dtran288, which instructions did you follow? The ones that I commented on here? I'm confused about why there is information related to QIIME in the error message, e.g., ``/home/qiime/qiime_software/``. Are you working in a QIIME Virtual Machine?

I'll likely need to get back to you tomorrow as I'm about to run for the day.

**Comment by dtran288** [comment]
@gregcaporaso  I followed the instructions on that you posted on Github.  I am on a QIIME virtual machine.  Or should I just run your instructions on different operating systems?  I also have windows 8 and Linux Mint.

**Comment by gregcaporaso** [comment]
Hmm, which version of the QIIME Virtual Box?

I'll give this a try tomorrow and see if I can reproduce the error to figure out what's going on. IAB won't work on Windows now (some of the dependencies don't work on Windows). It definitely does work on Ubuntu Linux, but it's possible that some of the configuration stuff in the default account on the QIIME Virtual Box is messing this up. As an alternative if you want to try to move forward with this now, you might try creating a new user account in the Virtual Box and seeing if those install instructions work then. 

I appreciate your feedback on this! I know it's frustrating, but it's extremely helpful to me to have people trying to use IAB in different environments.

**Comment by jg44** [comment]
From my side (on a Mac running 10.9):  

Thanks for your help.  I had installed python originally via anaconda, but I actually think the version I was running when I got scikit-bio working might have been the default Apple python (2.7) distribution.  I tried appending various things to my .bash_profile to force the default to be the anaconda-installed version, but I'm not sure that was ever successful.

I decided to try miniconda (in the spirit of testing the installation protocol for newbies like me) and followed the instructions to the T.  Everything seems to have worked okay all the way through.  There was a permissions error with the command:  "pip install https://github.com/gregcaporaso/An-Introduction-To-Applied-Bioinformatics/archive/0.1.1.tar.gz".  I "solved" this using "sudo pip install https://github.com/gregcaporaso/An-Introduction-To-Applied-Bioinformatics/archive/0.1.1.tar.gz" and it completed without errors.  This might have been a mistake though as now I'm back where I started with a non-functional scikit-bio (I think).  This time, however, it doesn't seem to be related to matplotlib not loading due to libpng16 issues (as before), but rather to libquadmath perhaps.

ipython loads and functions generally, but import skbio (and from iab.algorithms import format_matrix) kicks the following error string:

Sorry, I wish this were easy.  Maybe I have so many implementations of python from various attempts that I should uninstall somehow and start from scratch?  I don't know if conflicts are an issue.  scikit-bio works under certain environments but not others.  

Thanks...

import skbio
from __future__ import print_function
from IPython.core import page

page.page = print

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-cce712a72ed3> in <module>()
----> 1 import skbio
      2 from __future__ import print_function
      3 from IPython.core import page
      4 page.page = print

/Users/jeff/miniconda3/lib/python3.4/site-packages/skbio/__init__.py in <module>()
     13 
     14 # Add skbio.io to sys.modules to prevent cycles in our imports
---> 15 import skbio.io
     16 # imports included for convenience
     17 from skbio.sequence import (

/Users/jeff/miniconda3/lib/python3.4/site-packages/skbio/io/__init__.py in <module>()
    307 # registry. We use import_module instead of a typical import to avoid flake8
    308 # unused import errors.
--> 309 import_module('skbio.io.clustal')
    310 import_module('skbio.io.fasta')
    311 import_module('skbio.io.fastq')

/Users/jeff/miniconda3/lib/python3.4/importlib/__init__.py in import_module(name, package)
    107                 break
    108             level += 1
--> 109     return _bootstrap._gcd_import(name[level:], package, level)
    110 
    111 

/Users/jeff/miniconda3/lib/python3.4/site-packages/skbio/io/clustal.py in <module>()
    120 from skbio.io import (register_reader, register_writer, register_sniffer,
    121                       ClustalFormatError)
--> 122 from skbio.sequence import BiologicalSequence
    123 from skbio.alignment import Alignment
    124 

/Users/jeff/miniconda3/lib/python3.4/site-packages/skbio/sequence/__init__.py in <module>()
    151 from ._exception import (BiologicalSequenceError, GeneticCodeError,
    152                          GeneticCodeInitError, InvalidCodonError)
--> 153 from ._sequence import (BiologicalSequence, NucleotideSequence, DNASequence,
    154                         RNASequence, ProteinSequence, DNA, RNA, Protein)
    155 from ._genetic_code import GeneticCode, genetic_code

/Users/jeff/miniconda3/lib/python3.4/site-packages/skbio/sequence/_sequence.py in <module>()
     18 
     19 import numpy as np
---> 20 from scipy.spatial.distance import hamming
     21 
     22 from skbio._base import SkbioObject

/Users/jeff/miniconda3/lib/python3.4/site-packages/scipy/spatial/__init__.py in <module>()
     92 from .qhull import *
     93 from ._plotutils import *
---> 94 from ._procrustes import procrustes
     95 
     96 __all__ = [s for s in dir() if not s.startswith('_')]

/Users/jeff/miniconda3/lib/python3.4/site-packages/scipy/spatial/_procrustes.py in <module>()
      9 
     10 import numpy as np
---> 11 from scipy.linalg import orthogonal_procrustes
     12 
     13 

/Users/jeff/miniconda3/lib/python3.4/site-packages/scipy/linalg/__init__.py in <module>()
    170 from .linalg_version import linalg_version as __version__
    171 
--> 172 from .misc import *
    173 from .basic import *
    174 from .decomp import *

/Users/jeff/miniconda3/lib/python3.4/site-packages/scipy/linalg/misc.py in <module>()
      3 import numpy as np
      4 from numpy.linalg import LinAlgError
----> 5 from .blas import get_blas_funcs
      6 from .lapack import get_lapack_funcs
      7 

/Users/jeff/miniconda3/lib/python3.4/site-packages/scipy/linalg/blas.py in <module>()
    153 import numpy as _np
    154 
--> 155 from scipy.linalg import _fblas
    156 try:
    157     from scipy.linalg import _cblas

ImportError: dlopen(/Users/jeff/miniconda3/lib/python3.4/site-packages/scipy/linalg/_fblas.so, 2): Library not loaded: /usr/local/gfortran/lib/libquadmath.0.dylib
  Referenced from: /Users/jeff/miniconda3/lib/python3.4/site-packages/scipy/linalg/_fblas.so
  Reason: image not found

NOTE:  As an aside but possibly helpful, I tried steps 2-4 from your first post inside an environment where scikit-bio seems to be fully functional and got this error:

pip install https://github.com/gregcaporaso/An-Introduction-To-Applied-Bioinformatics/archive/0.1.1.tar.gz

(lots of error-free stuff omitted):

  error: library dfftpack has Fortran sources but no Fortran compiler found
    ----------------------------------------
Command "/Users/jeff/miniconda3/envs/env2/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/th/rykhc9555m39kztdx39dzj7r0000gp/T/pip-build-_pA8gu/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/th/rykhc9555m39kztdx39dzj7r0000gp/T/pip-Yvmn5b-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/th/rykhc9555m39kztdx39dzj7r0000gp/T/pip-build-_pA8gu/scipy

**Comment by dtran288** [comment]
Hello, I used virtualbox and downloaded ubuntu again.  This time seperate from QIIME with ubuntu, and I get a different error:

  Rolling back uninstall of pandas
Command "/home/dan/miniconda3/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-s7hlqdk0/pandas/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-p6hin0dk-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-s7hlqdk0/pandas

**Comment by gregcaporaso** [comment]
@dtran288, thanks for the update. I'm going to try to create a conda package for iab over the next day. I'll follow up here once I've done that.

**Comment by gregcaporaso** [comment]
@jg44, @dtran288, update on this. I have a test package up on conda now. If you want to try installing, after installing miniconda you should be able to run:

```bash
conda create --name iab-011 -c http://conda.binstar.org/gregcaporaso python=3.4 iab
```

This will create a new ``iab-011`` environment, and install IAB and its dependencies in it, and download the IAB notebooks. Once that completes, you should be able to run:

```bash
source activate iab-011
cd IAB-notebooks
ipython notebook index.ipynb
```

to get started. 

If you have a chance to give that a try and let me know if it works for you, that'd be really helpful. If all is looking good, I'll update the docs and this will be the default install procedure for IAB moving forward.

**Comment by jg44** [comment]
Worked for me!  Thank you so much for your help.

**Comment by gregcaporaso** [comment]
Great!

**Comment by gregcaporaso** [comment]
@jg44, did you install on OS X or Linux?

**Comment by jg44** [comment]
OSX 10.9 (Mavericks)

**Comment by gregcaporaso** [comment]
Thanks, that's what I thought. This won't work on Linux yet, but will soon.

**Comment by dtran288** [comment]
Oh, I'll wait for linux then.

**Comment by gregcaporaso** [comment]
@dtran288, those same commands work for me under Linux now after installing Miniconda. Want to give it a try?

**Comment by gregcaporaso** [comment]
These install instructions are now [in master](https://github.com/gregcaporaso/An-Introduction-To-Applied-Bioinformatics/blob/master/book/getting-started/reading-iab.md#installation-), but not yet updated on readIAB.org (they will be for the next release). Closing this issue as it should now be addressed by the conda install. Thanks again for the help @jg44 and @dtran288!

**Comment by dtran288** [comment]
Thank you!  It works now.

**Comment by gregcaporaso** [comment]
Awesome!
