### ISSUE TITLE
A statistical issue in 2.2.2 Is my alignment "good"? Determining whether an alignment is statistically significant.

### ISSUE THREAD

**Issue by ETaSky** [gregcaporaso/An-Introduction-To-Applied-Bioinformatics#171]
Dear Dr. Caporaso,

In section 2.2.2 Is my alignment "good"? Determining whether an alignment is statistically significant. In paragraph 2, you described "what we really want to know is: what fraction of the time would I obtain a score at least this good if my sequences are not homologous?" and in the following paragraph, you are referring this as alpha (false positive). Forgive me if I am a little bit picky, and I understand that positive and negative is a matter of definition. But if the we assume the null hypothesis is that the two sequences are homologous, then the above probability is actually false negative (beta), isn't it? Please correct me if I am wrong.
Thanks a lot!

Jincheng

**Comment by gregcaporaso** [comment]
Hi @ETaSky, Sorry for the very slow reply, but I'm catching up on issues now. Our null hypothesis is that the sequences are not homologous, and the alternative hypothesis is that they are.
