### ISSUE TITLE
typo in 3.1.6

### ISSUE THREAD

**Issue by gvanzin** [gregcaporaso/An-Introduction-To-Applied-Bioinformatics#172]
3.1.6
"You may have also heard of a method related to PCoA, called Principal Components Analysis or PCA. There is a key difference between these methods that is important for our useds."

Thanks for the great resource!

And just in case you want to recommend to your readers a great introductory text for data mining with Python...I've found it useful in understanding both the math and coding behind distance matrices, classifications, etc.

http://guidetodatamining.com

Thanks again,

Gary Vanzin

**Comment by gregcaporaso** [comment]
@gvanzin, it's really easy to edit the text to fix that typo if you're interested. See the wikipedia-style edit links next to the section headings. 

Thanks for the link, I'll check it out!
