### ISSUE TITLE
Unable to import iab.algorithms

### ISSUE THREAD

**Issue by sierra1bravo** [gregcaporaso/An-Introduction-To-Applied-Bioinformatics#173]
Hi
Here's a newbie question. I've installed Jupyter + IAB. Everything works fine until Box #7 (which has the the following line:

`from iab.algorithms import format_matrix`

This line gives an error stating `ImportError: No module named iab.algorithms`. What I am doing wrong ?

**Comment by gregcaporaso** [comment]
Hi @sierra1bravo, Did you follow the install instructions [here](http://readiab.org/book/latest/1/1#3)?

**Comment by sierra1bravo** [comment]
Thanks @gregcaporaso. I installed the whole thing again, and it works fine now. I suspect it is on account of installing some of the modules as superuser (I'm using Ubuntu).

**Comment by gregcaporaso** [comment]
Yep, that would do it. Glad it's working now!
