### ISSUE TITLE
Update to skbio v0.4.0

### ISSUE THREAD

**Issue by anderspitman** [gregcaporaso/An-Introduction-To-Applied-Bioinformatics#175]
Is there any desire to update the usage of skbio in IAB now that we have stability semantics in place?

**Comment by gregcaporaso** [comment]
Yes, definitely. What kind of updates are you thinking specifically?

**Comment by anderspitman** [comment]
I was just thinking 0.4.0, but if there's other low hanging fruit it might be worth hitting it in one go. May be best to wait for `TabularMSA` to stabilize though.

**Comment by ebolyen** [comment]
`TabularMSA` may not stabilize for a while, we would want to see how it interacts with everything else in the alignment subpackage first. I don't think we need it to be stable for IAB though?
