### ISSUE TITLE
ImportError: cannot import name '_hierarchy'

### ISSUE THREAD

**Issue by jg44** [gregcaporaso/An-Introduction-To-Applied-Bioinformatics#178]
Hello,

I recently (re)installed IAB using the following command:

conda create --name iab -c http://conda.binstar.org/gregcaporaso python=3.4 iab

(See: <https://github.com/gregcaporaso/An-Introduction-To-Applied-Bioinformatics/blob/master/book/getting-started/reading-iab.md#installation->)

I had earlier issues linked to this issue:  https://github.com/gregcaporaso/An-Introduction-To-Applied-Bioinformatics/issues/165#issuecomment-125396536

but I thought they were solved.  

Now I'm getting the following message about importing "heirarchy" when running the IAB notebook which I gather are again linked to the scipy installation.  See below.  I am on a Mac, OS 10.9.

Any thoughts?  Thanks,

Jeff

from iab.algorithms import format_matrix

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-f830f4e48990> in <module>()
----> 1 from iab.algorithms import format_matrix

/Users/jeff/miniconda3/lib/python3.4/site-packages/iab/algorithms/__init__.py in <module>()
     11 
     12 import numpy as np
---> 13 from scipy.cluster.hierarchy import average, dendrogram, to_tree
     14 from skbio.sequence import BiologicalSequence
     15 from skbio.stats.distance import DistanceMatrix

/Users/jeff/miniconda3/lib/python3.4/site-packages/scipy/cluster/__init__.py in <module>()
     25 __all__ = ['vq', 'hierarchy']
     26 
---> 27 from . import vq, hierarchy
     28 
     29 from numpy.testing import Tester

/Users/jeff/miniconda3/lib/python3.4/site-packages/scipy/cluster/hierarchy.py in <module>()
    173 
    174 import numpy as np
--> 175 from . import _hierarchy
    176 import scipy.spatial.distance as distance
    177 

ImportError: cannot import name '_hierarchy'

**Comment by gregcaporaso** [comment]
@jg44, sorry for the slow reply. I don't have the conda install working yet (it's in progress in #167). This will be the primary means of installation for 0.1.2, which will be released in December, 2015. For now, the best way to install is to follow the [install notes in the release version of the Getting Started chapter](http://readiab.org/book/latest/1/1#3). Sorry for the trouble!

**Comment by jg44** [comment]
Thanks.  I just can't get things working properly using the pip install.  Major problems with scipy on both Mac and Ubuntu.  I will just wait for the conda-based release.  Thanks for your response.

**Comment by gregcaporaso** [comment]
You should be able to conda install scipy, and then pip install IAB (pip
works within conda).
