### ISSUE TITLE
How-to install on Linux (maybe someone will find it helpful)

### ISSUE THREAD

**Issue by Ketochka** [gregcaporaso/An-Introduction-To-Applied-Bioinformatics#179]
Hi,

I had problems with executing code in IAB notebooks,
but now everything.
If someone has Linux Mint 17.2 or Linux Chakra, 
this method should help you:

1. Install Anaconda - Python3 (say it "yes" every time during setup)
2. Activate it: source bin/activate ~/anaconda3
3. Then: conda create --name iab-011 -c http://conda.binstar.org/gregcaporaso python=3.4 iab
source activate iab-011
4. cd IAB-notebooks
5. ipython notebook index.ipynb

Thanks :)
Olena

**Comment by gregcaporaso** [comment]
Hi @Ketochka, thanks for posting this. I'm planning to update the install notes to use conda in 0.1.2, which will be release in December, 2015, but I don't have it fully working yet. For now, my recommended install process is described [here](http://readiab.org/book/0.1.1/1/1#3) (though doing this in a Python 3 conda environment should also work).

**Comment by Ketochka** [comment]
Thank you for your response.
I tried to install through pip install, but got several errors and don't know why.
Now it seems a least working : I can execute code and see a result.
Will use this for now,
Please announce when everything is fully working.

**Comment by gregcaporaso** [comment]
I will, the best way to track announcements is via the new @readIAB twitter
account.
