### ISSUE TITLE
2.1.1 Figure one is missing or a broken link

### ISSUE THREAD

**Issue by lsl5** [gregcaporaso/An-Introduction-To-Applied-Bioinformatics#190]
Bear with me, this is my first contribution regarding readIAB.
Chapter 2, latest/2/1#1
Figure 1
2/images/alignment.png
404: File not found (I like your version @ caporasolab.us)
possible missing link to microtexture.png
Linda Lassiter (lsl5)

**Comment by gregcaporaso** [comment]
Thanks @lsl5! This was an oversight in some of my recent changes. I made the fix, should go live before too long (takes about an hour for the automating testing and then building the new website).

**Comment by gregcaporaso** [comment]
In the meantime, you can find the image [here](https://github.com/gregcaporaso/An-Introduction-To-Applied-Bioinformatics/blob/master/book/fundamentals/images/alignment.png).

**Comment by gregcaporaso** [comment]
Hmm, this still isn't working. Reopening the issue.
