### ISSUE TITLE
make notebooks run faster

### ISSUE THREAD

**Issue by jairideout** [gregcaporaso/An-Introduction-To-Applied-Bioinformatics#30]
The tests take ~40 minutes via Travis, which is running through all of the notebooks. Once we hit 50 minutes, Travis will abort the tests. Most of the cells run instantly, or with little delay, but some cells take several minutes to complete. @gregcaporaso thoughts on this?

Travis also requires that there is some sort of output printed within a 10-minute window, otherwise the tests will be killed. We're currently okay, but there are some cells that are likely close to this threshold.

**Comment by gregcaporaso** [comment]
This has mostly been addressed so closing this issue, but we desperately need a faster global aligner in scikit-bio (biocore/scikit-bio#254, biocore/scikit-bio#555)!
