### ISSUE TITLE
remove iab.algorithms.DNA when skbio dependency is updated beyond 0.1.4

### ISSUE THREAD

**Issue by gregcaporaso** [gregcaporaso/An-Introduction-To-Applied-Bioinformatics#56]
This light wrapper is required for the functionality introduced in [skbio's #507](https://github.com/biocore/scikit-bio/issues/507) which is used the MSA chapter, while IAB depends on skbio 0.1.4.

**Comment by jairideout** [comment]
Looks like these wrappers aren't in the codebase anymore, and IAB now relies on scikit-bio 0.2.3.
