### ISSUE TITLE
Embedded LaTeX doesn't always render properly on iPad

### ISSUE THREAD

**Issue by anderspitman** [gregcaporaso/An-Introduction-To-Applied-Bioinformatics#87]
I'm sure this is an upstream notebook issue, but thought it might be worth tracking here. I noticed it when reading through the pairwise section. If someone else can confirm that would be good.

**Comment by gregcaporaso** [comment]
@anderspitman, I cleaned up some of the latex on Friday, could you try again either with the 0.1.0 release, or the current master? If it's still bad, can you post a screenshot in this issue? If it's fixed now, can you close the issue? Thanks!

**Comment by anderspitman** [comment]
@gregcaporaso I'll take another look when I get back to my iPad.

**Comment by gregcaporaso** [comment]
Thanks, I tested on one and they looked ok, but it'd be great if you could double check.

**Comment by anderspitman** [comment]
LaTex looks great on latest master. The only other thing I noticed is that some of the tables (ASCII text) are too many columns for the iPad in portrait mode, so you have to use landscape, but I don't think that's a real problem.
