### ISSUE TITLE
add a table of contents object

### ISSUE THREAD

**Issue by gregcaporaso** [gregcaporaso/An-Introduction-To-Applied-Bioinformatics#98]
This would probably be a ``pd.DataFrame`` with a multi-index, but I need a single object that I can query to get chapter names and links, rather than hard-coding these through-out the text. This might be a little clunky because you can't execute python code in a markdown cell, but that will be better than having broken links and outdated chapter names scattered throughout the text.

**Comment by gregcaporaso** [comment]
The way to handle the references is probably with some kind of box that could be in an executable python cell that we'd just drop after the referring text. For example, something like this (but obviously less hideous):

![screenshot 2015-03-30 10 00 38](https://cloud.githubusercontent.com/assets/192372/6901677/b8989a48-d6c3-11e4-9421-5a0ffe10888d.png)

This is similar to what I have in mind for #76.

**Comment by ebolyen** [comment]
@gregcaporaso that solution should be pretty straight-forward. I might have time this week to work on that if you'd like.

**Comment by gregcaporaso** [comment]
All chapters currently have issues with the *chapter* label. See [here](https://github.com/gregcaporaso/An-Introduction-To-Applied-Bioinformatics/labels/chapter). One of the pieces of metadata associated with each chapter should ultimately be its GitHub issue number.

**Comment by gregcaporaso** [comment]
[Here](https://docs.google.com/spreadsheets/d/1ipE7Uc_EnubWFTZd9P7YsxjWX_nNLL1yOsDoJxxX0Ns/pubhtml?gid=0&single=true)'s a prototype of what the data frame TOC might ultimately look like. I'm going to keep this updated and use it until we have a page with all of this information.

**Comment by gregcaporaso** [comment]
This is now complete as part of #140 and through [gregcaporaso/build-iab](github.com/gregcaporaso/build-iab).
